# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # 这是用于Vite项目的配置
  - package-ecosystem: "pnpm" # 使用npm作为包管理器
    directory: "/" # 项目根目录
    schedule:
      interval: "weekly" # 每周检查更新
    commit-message:
      prefix: "deps"
      include: scope
