/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/AvatarImage.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardContent: typeof import('./src/components/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/CardDescription.vue')['default']
    CardHeader: typeof import('./src/components/CardHeader.vue')['default']
    CardStack: typeof import('./src/components/CardStack.vue')['default']
    CardTitle: typeof import('./src/components/CardTitle.vue')['default']
    DesktopMenu: typeof import('./src/components/Header/DesktopMenu.vue')['default']
    DeviceInfoTable: typeof import('./src/components/Form/DeviceInfoTable.vue')['default']
    FeedBack: typeof import('./src/components/Form/FeedBack.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GalleryCard: typeof import('./src/components/Cards/GalleryCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MasonryGallery: typeof import('./src/components/Gallery/MasonryGallery.vue')['default']
    MentorCard: typeof import('./src/components/Cards/MentorCard.vue')['default']
    MenuIcon: typeof import('./src/components/MenuIcon.vue')['default']
    MobileDropdownMenu: typeof import('./src/components/Header/MobileDropdownMenu.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    PitScoutingDashboard: typeof import('./src/components/PitScoutingDashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMember: typeof import('./src/components/Member/TeamMember.vue')['default']
    TeamSection: typeof import('./src/components/Member/TeamSection.vue')['default']
    WinnerBanner: typeof import('./src/components/Cards/WinnerBanner.vue')['default']
  }
}
