name: Deploy to HTML Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "10.14.0"
        run_install: false

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Deploy build files to webpage branch
      run: |
        set -e

        # Configure git identity
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Ensure dist exists
        if [ ! -d dist ]; then
          echo "Error: dist folder not found"
          exit 1
        fi

        # Fetch the existing webpage branch if it exists
        git fetch origin webpage:webpage || echo "No existing webpage branch"

        # Create or checkout webpage branch
        if git rev-parse --verify webpage >/dev/null 2>&1; then
          git checkout webpage
        else
          git checkout --orphan webpage
        fi

        # Clean old files in webpage branch
        if [ "$(git branch --show-current)" = "webpage" ]; then
          git clean -fdx
        fi

        # Copy build files from master branch
        git checkout master -- dist
        cp -a dist/. .

        # Commit and push changes
        git add .

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "[Auto CI] Update build files from commit $GITHUB_SHA"
          git push origin webpage
        fi
